### ISSUE TITLE
v0.1.6 fails to build on nightly

### ISSUE THREAD

**Issue by maximih** [crossbeam-rs/crossbeam#75]
```
/Users/mX/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.1.6/src/sync/seg_queue.rs:34:29: 34:43 error: transmute called with differently sized types: [usize; 32] (2048 bits) to [std::sync::atomic::AtomicBool; 32] (256 bits) [E0512]
/Users/mX/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.1.6/src/sync/seg_queue.rs:34             ready: unsafe { mem::transmute([0usize; SEG_SIZE]) },
                                                                                                                               ^~~~~~~~~~~~~~
/Users/mX/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.1.6/src/sync/seg_queue.rs:34:29: 34:43 help: run `rustc --explain E0512` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
error: Could not compile `crossbeam`.
```

```
$ rustc --version
rustc 1.10.0-nightly (267cde259 2016-05-25)
```

**Comment by maximih** [comment]
I guess same as https://github.com/rust-lang/rust/issues/33724, which is caused by https://github.com/rust-lang/rust/pull/33579

**Comment by maximih** [comment]
I know v0.1.6 is a quite an old version but it's used by [simple_parallel](https://crates.io/crates/simple_parallel)

**Comment by antoyo** [comment]
Now, it does not even work on stable rust (1.10).

**Comment by stjepang** [comment]
Is this still a problem that needs to be fixed?

**Comment by maximih** [comment]
I removed my dependency on simple_parallel so I have no idea if this is still an issue.

**Comment by antoyo** [comment]
I still get this error when running the simple_parallel example:
```
error[E0512]: transmute called with differently sized types: [usize; 32] (2048 bits) to [std::sync::atomic::AtomicBool; 32] (256 bits)
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-0.1.6/src/sync/seg_queue.rs:34:29
   |
34 |             ready: unsafe { mem::transmute([0usize; SEG_SIZE]) },
   |                             ^^^^^^^^^^^^^^ transmuting between 2048 bits and 256 bits

error: aborting due to previous error(s)
```

**Comment by stjepang** [comment]
The problem can be fixed by bumping the crossbeam dependency to version 0.2.x. There was an effort to do that [here](https://github.com/huonw/simple_parallel/issues/9), but it seems like simple_parallel is totally abandoned and won't be maintained anymore. It's superseded by rayon anyway, which should be better in every way.

Crossbeam is going through a revamp right now. Version 0.1.x is really old and shouldn't be used, so I don't see a good motivation to patch it. For that reason I'm closing this issue, but if you'd *really* like to have this fixed, do let me know. :)
